accounts/urls.py
from django.urls import path
from . import views

# URLS.py OF ACCOUNTS APP
app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('addmovies/', views.add_movies, name="add_movies"),
    path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletemovies/<int:id>/', views.delete_movies, name="delete_movie"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review")


]

moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie(models.Model):
    # fields for the movie table
    name = models.CharField(max_length=300)
    imdb = models.URLField(max_length = 200)
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)
    description = models.CharField(max_length=1000, null=True, default=None)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=100000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


#create a Movie Form:-
class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'imdb', 'image', 'description')
        labels = {
            'name': '',
            'imdb': '',
            'image': '',
            'description': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please Input the Movie Name Here'}),
            'imdb': forms.URLInput(attrs={'class':'form-control', 'placeholder':'An IMDb link of the Movie Here..'}),
            'image': forms.URLInput(attrs={'class':'form-control', 'placeholder':'And a LINK to a picture of the Movie, from the Internet, right here!'}),
            'description': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Please Input the Movie Description Here'}),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = {"comment", "rating"}

        labels = {
            'comment': '',
            'rating': '',
        }

        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control', 'placeholder': 'Comment'}),
            'rating': forms.NumberInput(attrs={'class':'form-control', 'placeholder': 'Rating'})
        }

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.db.models import Avg
from django.contrib.auth.models import User
from django.core.paginator import Paginator

# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__contains=query)
    else:
        allMovies = Movie.objects.all() # select * from movie
        paginator = Paginator(allMovies, per_page= 6)

    context = {
        "movies": allMovies,

    }

    return render(request, 'main/index.html', context)

# detail page
def detail(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=id).order_by('-id')


    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    context = {
        "movie": movie,
        "reviews": reviews,
        "average": average,

    }
    return render(request, 'main/details.html', context)

# def main(request):
#     return render(request, 'base.html')

#add movies to the database
# def add_movies(request):
#     if request.method == "POST":
#         form = MovieForm(request.POST or None)

#         #check if form is valid:
#         if form.is_valid():
#             data = form.save(commit=False)
#             data.save()
#             return redirect("main:home")
#         else:
#             form = MovieForm()
#         return render(request, 'main/addmovies.html', {"form": form})

def add_movies(request):
    if request.user.is_authenticated:

        if request.user.is_superuser:
            submitted = False
            if request.method == "POST":
                form = MovieForm(request.POST)
                if form.is_valid():
                    form.save()
                    return HttpResponseRedirect('/addmovies?submitted=True')
            else:
                form = MovieForm
                if 'submitted' in request.GET:
                    submitted=True


            return render(request, 'main/addmovies.html', {"form": form, "controller": "Add Movie", 'submitted':submitted})
        #if they are not admin
        else:
            return redirect("main:home")
    #if they are not logged in
    else:
        return redirect("accounts:login")

def edit_movies(request, id):
    if request.user.is_authenticated:

        if request.user.is_superuser:
    # submitted = False
            movie = Movie.objects.get(id=id)

            if request.method == "POST":
                form = MovieForm(request.POST or None, instance=movie)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = MovieForm(instance=movie)
            # return HttpResponseRedirect('main/addmovies?submitted=True')
            return render(request, 'main/addmovies.html', {"form": form, "controller": "Edit Movie"})
         #if they are not admin
        else:
            return redirect("main:home")
    #if they are not logged in
    else:
        return redirect("accounts:login")

#delete movies
def delete_movies(request, id):
    if request.user.is_authenticated:

        if request.user.is_superuser:
            #get the movie
            movie = Movie.objects.get(id=id)

            #delete the movie
            movie.delete()
            return redirect("main:home")

         #if they are not admin
        else:
            return redirect("main:home")
    #if they are not logged in
    else:
        return redirect("accounts:login")


def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")


def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        #review
        review = Review.objects.get(movie=movie, id=review_id)

        #check if the review was done by the logged in user
        if request.user == review.user:
            #grant permission
            if request.method == "POST" or "GET":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = "Out of range. Please select rating from 0 to 10."
                        return render(request, 'main/editreview.html', {"error": error, "form":form})
                    else:

                        data.save()
                        return redirect("main:detail", movie_id)
                else:
                    form = ReviewForm(instance=review)
                return render(request, 'main/editreview.html', {"form": form})
            else:
                return redirect("main:detail", movie_id)
        else:
            return redirect("accounts:login")


#Delete review:
def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        #review
        review = Review.objects.get(movie=movie, id=review_id)

        #check if the review was done by the logged in user
        if request.user == review.user:
            #grant permission to delete
            review.delete()

        return redirect("main:detail", movie_id)
    else:
        return redirect("accounts:login")

main/templates/main/addmovies.html
{% extends 'main/base.html'  %}



{% block content %}

<br><br>
<div class="container" style="background-color: #a7d129">
    <br>
    <div class="card" style="background-color: #a7d129">
        <div class="card-body" style="background-color: #3e3636">

                <center>
                    <H1 style="color: white">{{ controller }}</H1>

                <br><br>
                {% if submitted %}
                    <h3 style="color: white">Your Movie was Submitted Successfully!!!</h3>
                {% else %}


                <form action="" method=POST style="color: white">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <input type="submit" value="{{ controller }}" class="btn btn-success">

                </form>
                {% endif %}
                </center>
        </div>
    </div>
    <br>
</div>

<!-- <div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Movie</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add Movies">
            </form>
        </div>
    </div>
</div> -->

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Sj's Movie Reviews</title>

  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark text-white" style="background-color: #000; background-image:linear-gradient(#414141,#000000)">
      <a class="navbar-brand" href="{% url 'main:home' %}">Sj's Movie Reviews</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

         <!--  <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
          </li> -->
         <!--  <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li> -->
          <!-- ADD MOVIE LINK BUTTON -->
          {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movies</a>
                </li>
            {% endif %}
          {% endif %}


          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          </li>
          {% endif %}

        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Search Movies" aria-label="Search" name="title" value="{{ request.GET.title }}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container" style="background-color: #a7d129">
    <br>
    <div class="card" >
        <div class="card-body" style="color: #f7f7e9; background-color: #3e3636">
        <div class="row">
            <div class="col-md-4">
                <img src="{{movie.image}}" alt="{{movie.name}}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <div class="text-center">
                    <h2 class="text-center">{{movie.name}}</h2>
                    <br>
                    <br>
                    <h4><a href="{{ movie.imdb }}" class="btn btn-warning">IMDb</a></h4>
                    <br>
                    <h4>Average Rating: {{ average }} / 10 </h4>
                    <br><br>
                    <h5>Description: {{movie.description}}</h5>
                    <br><br>
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a>
                            <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete Movie</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        </div>

        <div class="card" style="background-color: #a7d129">
            <div class="card-body" style="color: #f7f7e9; background-color: #3e3636">
                <h3 class="text-center">Add Review</h3>
                <form action="{% url 'main:add_review' movie.id %}" method="POST">
                    {% csrf_token %}

                    <textarea placeholder="Review" color="#fff" name="comment" id="comment" cols="30" rows="5" class="form-control" style="color: white; background-image: linear-gradient(#81a362, #403d37);"></textarea>

                    <br>
                    <label for="rating">Rating:</label>
                    <br>
                    <input type="range" id="rangeInput" name="rating" min="0" max="10" value="0" step="0.1" oninput="amount.value=rangeInput.value">

                    <output name="amount" id="amount" for="rangeInput">0</output>
                    <br>
                    <center>
                    <input type="submit" class="btn btn-success" value="Add Review">
                    </center>
                </form>
            </div>
        </div>

        <div class="card"  >
            <div class="card-body" style="background-color: #3e3636">
                <h3 class="text-center" style="color: #f7f7e9" style = "font-family:courier new, courier, Times New Roman; font-weight: bold;">Reviews</h3>
                <br>
                {% for review in reviews %}

                    <div class="card" style="background-color: #3e3636">
                        <div class="card-body" style="background-color: #3e3636; border-radius: 8px;">
                            <div class="row" style="padding-bottom: 10px;background-color: #d5e398; background-image: linear-gradient(#56ab2f, #a8e063); border-radius: 8px;">
                                <div class="col-md-3">
                                    <br>
                                    <h5 class="text-left" style = "font-family:courier new, courier, Times New Roman; font-weight: bold;">{{ review.user.username }}</h5>
                                    <h5 style = "font-family:courier, courier, Times New Roman; font-weight: bold;">{{ review.rating }}</h5>

                                    {% if request.user == review.user %}
                                    <a style = "border-radius: 8px;border-style:solid;border-color:#c48c23;font-family: courier, courier, Times New Roman; font-weight: bold;" href="{% url 'main:edit_review' movie.id review.id %}" class="btn btn-warning btn-sm">Edit</a>
                                    <a style = "border-radius: 8px;border-style:solid ; border-color:#54120d ;font-family: courier, courier, Times New Roman; font-weight: bold;" href="{% url 'main:delete_review' movie.id review.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this?');">Delete</a><br>
                                    {% endif %}

                                </div>
                                <div class="col-md-9">
                                    <br>
                                    <p style = "font-family:courier, courier, Times New Roman; font-weight: bold; ">{{ review.comment }}</p>

                                </div>


                            </div>
                        </div>


                        {% endfor %}
                    </div>
            </div>
        </div>





    </div>
    <br>
</div>
<br>

{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html'  %}



{% block content %}

<br><br>
<div class="container" style="background-color: #a7d129">
    <br>
    <div class="card" style="background-color: #a7d129">
        <div class="card-body" style="background-color: #3e3636">

                <center>
                    <H1 style="color: white">Edit Review</H1>

                <br><br>

                <form action="" method=POST style="color: white">
                    {% csrf_token %}

                    {{ form.as_p }}

                    {% if error %}
                        <strong style="color: red;">{{ error }}</strong><br><br>
                    {% endif %}
                    <input type="submit" value="Save Changes" class="btn btn-success">

                </form>
                </center>
        </div>
    </div>
    <br>
</div>

<!-- <div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Movie</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add Movies">
            </form>
        </div>
    </div>
</div> -->

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body" >
            <div class="row" >
                {% for movie in movies %}
                <div class="col-md-4" >
                    <div class="card" id="cardbg">

                        <div class="card-body" >

                            <div class="text-center">
                                <img src="{{movie.image}}" alt="" class="img-fluid" width="75%" height="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>

                            <a href="{% url 'main:detail' movie.id %}" class="btn btn-success">Read More</a>
                            </div>

                        </div>

                    </div>
                    <br>
                </div>

                {% endfor %}
            </div>
        </div>
    </div>

</div>


{% endblock %}